# Default values for metatron-single.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

discovery:
  name: discovery
  image: bocesr/metatron-discovery
  tag: latest
  imagePullPolicy: IfNotPresent

  resources: {}
  affinity: {}
  tolerations: {}

  service:
    type: ClusterIP

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi

druid:
  name: druid
  image: bocesr/metatron-druid
  tag: latest
  imagePullPolicy: IfNotPresent

  resources: {}
  affinity: {}
  tolerations: {}

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 5Gi
  
  service:
    type: ClusterIP
  
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local